# Generated by Django 5.1.6 on 2025-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, upload_to="menu_items/"),
        ),
    ]
