# Generated by Django 5.1.6 on 2025-02-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_menuitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="location",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="photo",
        ),
    ]
