# Generated by Django 5.1.6 on 2025-03-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_remove_menuitem_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="category_title",
        ),
        migrations.RenameField(
            model_name="menuitem",
            old_name="title",
            new_name="menu_item_title",
        ),
    ]
